-- 补全表、字段中文注释（不改结构）
SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE sys_user
    COMMENT = '系统用户',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN username VARCHAR(64) NOT NULL COMMENT '登录名',
    MODIFY COLUMN password_hash VARCHAR(120) NOT NULL COMMENT '密码哈希',
    MODIFY COLUMN display_name VARCHAR(64) NOT NULL COMMENT '显示名',
    MODIFY COLUMN enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用：1是 0否',
    MODIFY COLUMN must_change_pwd TINYINT NOT NULL DEFAULT 0 COMMENT '是否必须改密：1是 0否',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：1是 0否';

ALTER TABLE sys_role
    COMMENT = '角色',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN code VARCHAR(64) NOT NULL COMMENT '角色编码，如 admin / analyst',
    MODIFY COLUMN name VARCHAR(64) NOT NULL COMMENT '角色名称',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：1是 0否';

ALTER TABLE sys_permission
    COMMENT = '权限（菜单/按钮）',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN code VARCHAR(64) NOT NULL COMMENT '权限编码',
    MODIFY COLUMN name VARCHAR(64) NOT NULL COMMENT '权限名称',
    MODIFY COLUMN type VARCHAR(16) NOT NULL COMMENT '类型：MENU 菜单 / BUTTON 按钮',
    MODIFY COLUMN parent_code VARCHAR(64) NULL COMMENT '上级权限编码',
    MODIFY COLUMN path VARCHAR(128) NULL COMMENT '前端路由，仅菜单使用',
    MODIFY COLUMN sort_no INT NOT NULL DEFAULT 0 COMMENT '排序号，越小越靠前';

ALTER TABLE sys_user_role
    COMMENT = '用户角色关系',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '用户ID',
    MODIFY COLUMN role_id BIGINT NOT NULL COMMENT '角色ID';

ALTER TABLE sys_role_permission
    COMMENT = '角色权限关系',
    MODIFY COLUMN role_id BIGINT NOT NULL COMMENT '角色ID',
    MODIFY COLUMN permission_id BIGINT NOT NULL COMMENT '权限ID';

ALTER TABLE project
    COMMENT = '口碑分析项目',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN name VARCHAR(128) NOT NULL COMMENT '项目名称',
    MODIFY COLUMN category VARCHAR(64) NULL COMMENT '品类',
    MODIFY COLUMN brand VARCHAR(64) NULL COMMENT '品牌',
    MODIFY COLUMN main_model VARCHAR(128) NULL COMMENT '主型号',
    MODIFY COLUMN competitors JSON NULL COMMENT '竞品列表',
    MODIFY COLUMN keywords JSON NULL COMMENT '监测关键词',
    MODIFY COLUMN platforms JSON NULL COMMENT '平台勾选，仅表示期望范围',
    MODIFY COLUMN time_start DATE NULL COMMENT '监测开始日期',
    MODIFY COLUMN time_end DATE NULL COMMENT '监测结束日期',
    MODIFY COLUMN owner_id BIGINT NOT NULL COMMENT '负责人用户ID',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：1是 0否';

ALTER TABLE project_member
    COMMENT = '项目成员',
    MODIFY COLUMN project_id BIGINT NOT NULL COMMENT '项目ID',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '用户ID';

ALTER TABLE import_job
    COMMENT = '评论导入任务',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN project_id BIGINT NOT NULL COMMENT '项目ID',
    MODIFY COLUMN type VARCHAR(32) NOT NULL DEFAULT 'IMPORT' COMMENT '任务类型，默认 IMPORT',
    MODIFY COLUMN filename VARCHAR(255) NOT NULL COMMENT '原始文件名',
    MODIFY COLUMN object_key VARCHAR(512) NOT NULL COMMENT '对象存储中的文件路径',
    MODIFY COLUMN status VARCHAR(32) NOT NULL COMMENT '状态：PENDING / IMPORTING / READY / FAILED 等',
    MODIFY COLUMN total_rows INT NOT NULL DEFAULT 0 COMMENT '总行数',
    MODIFY COLUMN success_rows INT NOT NULL DEFAULT 0 COMMENT '成功行数',
    MODIFY COLUMN fail_rows INT NOT NULL DEFAULT 0 COMMENT '失败行数',
    MODIFY COLUMN error_object_key VARCHAR(512) NULL COMMENT '失败行报告文件路径',
    MODIFY COLUMN message VARCHAR(512) NULL COMMENT '任务说明或失败原因',
    MODIFY COLUMN created_by BIGINT NOT NULL COMMENT '创建人用户ID',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE review
    COMMENT = '原始评论及清洗、情感结果',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN project_id BIGINT NOT NULL COMMENT '项目ID',
    MODIFY COLUMN import_job_id BIGINT NULL COMMENT '来源导入任务ID',
    MODIFY COLUMN platform VARCHAR(32) NOT NULL COMMENT '平台：xiaohongshu / jd / taobao / douyin',
    MODIFY COLUMN product_id VARCHAR(128) NULL COMMENT '商品ID',
    MODIFY COLUMN review_id VARCHAR(128) NOT NULL COMMENT '平台评论ID，无则用内容哈希',
    MODIFY COLUMN content TEXT NOT NULL COMMENT '评论文本',
    MODIFY COLUMN review_time DATETIME NULL COMMENT '评论时间',
    MODIFY COLUMN like_count INT NOT NULL DEFAULT 0 COMMENT '点赞数',
    MODIFY COLUMN author_hash VARCHAR(128) NULL COMMENT '作者匿名标识',
    MODIFY COLUMN product_name VARCHAR(255) NULL COMMENT '商品名',
    MODIFY COLUMN source_url VARCHAR(512) NULL COMMENT '溯源链接',
    MODIFY COLUMN raw_payload JSON NULL COMMENT '导入原始行',
    MODIFY COLUMN content_hash VARCHAR(64) NOT NULL COMMENT '正文哈希，用于去重',
    MODIFY COLUMN clean_tags VARCHAR(255) NULL COMMENT '清洗标记：duplicate / ad / short / masked',
    MODIFY COLUMN clean_reason VARCHAR(512) NULL COMMENT '清洗说明',
    MODIFY COLUMN aspect_hits VARCHAR(255) NULL COMMENT '命中的方面名，逗号分隔',
    MODIFY COLUMN sentiment VARCHAR(8) NULL COMMENT '整评情感：正 / 负 / 中',
    MODIFY COLUMN sentiment_reason VARCHAR(255) NULL COMMENT '整评情感原因',
    MODIFY COLUMN sentiment_confidence DECIMAL(4,3) NULL COMMENT '整评情感置信度',
    MODIFY COLUMN analyze_source VARCHAR(16) NULL COMMENT '分析来源：rule / llm',
    MODIFY COLUMN counted TINYINT NOT NULL DEFAULT 1 COMMENT '是否计入有效评论：1是 0否',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '入库时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：1是 0否';

ALTER TABLE pipeline_job
    COMMENT = '清洗与分析流水线任务',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN project_id BIGINT NOT NULL COMMENT '项目ID',
    MODIFY COLUMN type VARCHAR(32) NOT NULL COMMENT '类型：CLEAN / ANALYZE 等',
    MODIFY COLUMN status VARCHAR(32) NOT NULL COMMENT '状态：PENDING / CLEANING / ANALYZING / INDEXING / READY / FAILED 等',
    MODIFY COLUMN message VARCHAR(512) NULL COMMENT '进度说明或失败原因',
    MODIFY COLUMN created_by BIGINT NOT NULL COMMENT '触发人用户ID',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE review_aspect
    COMMENT = '单条评论的方面情感明细',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN project_id BIGINT NOT NULL COMMENT '项目ID',
    MODIFY COLUMN review_id BIGINT NOT NULL COMMENT '评论ID',
    MODIFY COLUMN aspect_name VARCHAR(64) NOT NULL COMMENT '方面名，须落在词典或「其它」',
    MODIFY COLUMN sentiment VARCHAR(8) NOT NULL COMMENT '方面情感：正 / 负 / 中',
    MODIFY COLUMN reason VARCHAR(255) NULL COMMENT '方面原因短句',
    MODIFY COLUMN confidence DECIMAL(4,3) NOT NULL DEFAULT 0.500 COMMENT '置信度',
    MODIFY COLUMN source VARCHAR(16) NOT NULL DEFAULT 'rule' COMMENT '来源：rule / llm',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE evidence
    COMMENT = '报告可用证据（方面原声）',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN project_id BIGINT NOT NULL COMMENT '项目ID',
    MODIFY COLUMN review_id BIGINT NOT NULL COMMENT '评论ID',
    MODIFY COLUMN aspect_name VARCHAR(64) NOT NULL COMMENT '方面名',
    MODIFY COLUMN sentiment VARCHAR(8) NOT NULL COMMENT '方面情感：正 / 负 / 中',
    MODIFY COLUMN quote VARCHAR(255) NULL COMMENT '原声摘录',
    MODIFY COLUMN source VARCHAR(16) NOT NULL DEFAULT 'rule' COMMENT '来源：rule / llm',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE llm_provider
    COMMENT = '大模型提供方',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN name VARCHAR(64) NOT NULL COMMENT '提供方名称',
    MODIFY COLUMN protocol VARCHAR(32) NOT NULL DEFAULT 'openai_compat' COMMENT '协议，默认 openai_compat',
    MODIFY COLUMN base_url VARCHAR(255) NOT NULL COMMENT '接口根地址',
    MODIFY COLUMN api_key_cipher TEXT NULL COMMENT '加密后的 API Key',
    MODIFY COLUMN api_key_suffix VARCHAR(8) NULL COMMENT 'Key 末几位，列表脱敏展示',
    MODIFY COLUMN extra_headers JSON NULL COMMENT '额外请求头',
    MODIFY COLUMN enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用：1是 0否',
    MODIFY COLUMN timeout_ms INT NOT NULL DEFAULT 60000 COMMENT '超时毫秒',
    MODIFY COLUMN max_retry INT NOT NULL DEFAULT 1 COMMENT '最大重试次数',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：1是 0否';

ALTER TABLE llm_model
    COMMENT = '提供方下的模型',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN provider_id BIGINT NOT NULL COMMENT '提供方ID',
    MODIFY COLUMN model_code VARCHAR(128) NOT NULL COMMENT '模型编码',
    MODIFY COLUMN context_length INT NULL COMMENT '上下文长度',
    MODIFY COLUMN json_mode TINYINT NOT NULL DEFAULT 1 COMMENT '是否按 JSON 输出：1是 0否',
    MODIFY COLUMN input_price DECIMAL(12,6) NULL COMMENT '输入单价（可选）',
    MODIFY COLUMN output_price DECIMAL(12,6) NULL COMMENT '输出单价（可选）',
    MODIFY COLUMN enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用：1是 0否',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：1是 0否';

ALTER TABLE llm_route
    COMMENT = '按用途指定主备模型',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN purpose_code VARCHAR(64) NOT NULL COMMENT '用途：absa / sentiment / report_summary / embedding / spam_classify',
    MODIFY COLUMN primary_model_id BIGINT NULL COMMENT '主模型ID',
    MODIFY COLUMN backup_model_id BIGINT NULL COMMENT '备用模型ID',
    MODIFY COLUMN enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用：1是 0否',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：1是 0否';

ALTER TABLE llm_usage
    COMMENT = '模型调用用量记录',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN purpose_code VARCHAR(64) NOT NULL COMMENT '用途编码',
    MODIFY COLUMN provider_id BIGINT NULL COMMENT '提供方ID',
    MODIFY COLUMN model_id BIGINT NULL COMMENT '模型ID',
    MODIFY COLUMN model_code VARCHAR(128) NULL COMMENT '当时使用的模型编码',
    MODIFY COLUMN job_id BIGINT NULL COMMENT '关联流水线任务ID',
    MODIFY COLUMN project_id BIGINT NULL COMMENT '项目ID',
    MODIFY COLUMN prompt_tokens INT NOT NULL DEFAULT 0 COMMENT '输入 token 数',
    MODIFY COLUMN completion_tokens INT NOT NULL DEFAULT 0 COMMENT '输出 token 数',
    MODIFY COLUMN total_tokens INT NOT NULL DEFAULT 0 COMMENT '总 token 数',
    MODIFY COLUMN success TINYINT NOT NULL DEFAULT 1 COMMENT '是否成功：1是 0否',
    MODIFY COLUMN detail VARCHAR(255) NULL COMMENT '失败原因或备注',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '调用时间';

ALTER TABLE aspect_dict
    COMMENT = '方面词典',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN name VARCHAR(64) NOT NULL COMMENT '方面名，如亮度、色温',
    MODIFY COLUMN keywords VARCHAR(255) NULL COMMENT '匹配关键词，逗号分隔',
    MODIFY COLUMN sort_no INT NOT NULL DEFAULT 0 COMMENT '排序号，越小越靠前',
    MODIFY COLUMN enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用：1是 0否',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：1是 0否';

ALTER TABLE audit_log
    COMMENT = '操作日志',
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN user_id BIGINT NULL COMMENT '操作人用户ID',
    MODIFY COLUMN username VARCHAR(64) NULL COMMENT '操作人登录名',
    MODIFY COLUMN action VARCHAR(64) NOT NULL COMMENT '动作编码',
    MODIFY COLUMN resource VARCHAR(64) NULL COMMENT '对象类型',
    MODIFY COLUMN detail TEXT NULL COMMENT '详情',
    MODIFY COLUMN ip VARCHAR(64) NULL COMMENT '来源 IP',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间';
